SLT-800: Drupal: Cron: Exit Code: Fix. Comments: Add.

diff --git a/charts/drupal/templates/drupal-cron.yaml b/charts/drupal/templates/drupal-cron.yaml
--- a/charts/drupal/templates/drupal-cron.yaml
+++ b/charts/drupal/templates/drupal-cron.yaml
@@ -35,15 +35,17 @@ spec:
                 {{- include "cron.entrypoints" $ | nindent 16 }}
                 set -x
                 if [ {{ include "drupal.installation-in-progress-test" $ }} ]; then
-                  # Retry util install finishes
+                  # Retry util install finishes.
                   exit 1
                 fi
-                # Disable debugging while setting up things
+
+                # Disable debugging while setting up things.
+                # Don't output the set command itself.
                 { set +x ; } 2>/dev/null
-                set +e
+
                 # We need to save the executable command(s) into a file,
-                # because 'time' can exeute only command-files,
-                # not shell constructs.
+                # because the 'time' can exeute only command-files,
+                # not the shell constructs.
                 script="/tmp/cron.$$"
                 cat << CMD > "${script}"
                 #!/bin/bash
@@ -51,23 +53,41 @@ spec:
                 {{ $job.command | nindent 16 }}
                 CMD
                 chmod 755 "${script}"
+
+                # Try to make the tmp files more unique.
+                # $$ = pid of current running shell.
                 stats="/tmp/stats.$$"
                 output="/tmp/output.$$"
                 output_json="/tmp/output_json.$$"
-                # The execution.
-                /usr/bin/time -f '"time_s":%e,"peak_mem_kb":%M' -o "${stats}" "${script}" 2>&1 \
+
+                # The execution of the actual cron command.
+                # For backwards compatibility reasons sent the output to stdout as well (tee).
+                /usr/bin/time -f '"elapsed_time_s":%e,"peak_mem_kb":%M' -o "${stats}" "${script}" 2>&1 \
                 | tee "${output}"
-                exit_code="$?"
+
+                # It's tricky to get exit code of a random command from a pipeline.
+                # It is highly shell-dependent.
+                exit_code="${PIPESTATUS[0]}"
+
+                # Convert the command output to json.
                 php -r 'print json_encode(file_get_contents("/dev/stdin"))."\n";' < "${output}" > "${output_json}"
+
+                # If the error code is non-zero,
+                # the output file contains also a warning,
+                # which is not json.
+                # Get rid of this.
+                stats="$(grep -E '"elapsed_time_s".*"peak_mem_kb"' ${stats})"
+
                 cron_name="{{ $index }}"
-                # if the error code is non-zero, the output file contains a warning.
-                stats="$(grep -E '"time_s".*"peak_mem_kb"' ${stats})"
+
                 # Assemble the JSON output.
                 cat << JSON
                 {"cron_name":"${cron_name}",${stats},"exit_code":${exit_code},"output":$(cat "${output_json}")}
                 JSON
-                # Prevent loop when a job fails.
-                exit 0
+
+                # Use the exit code of the actual cron command.
+                exit "$exit_code"
+
             resources:
               {{ if $job.resources }}
               {{- $job.resources | toYaml | nindent 14 }}
